# Análise de dados de uma variável

## Introdução

> A ideia de uma análise descritiva de dados é tentar responder as seguintes questões:
>
> i) Qual a frequência com que cada valor (ou intervalo de valores) aparece no conjunto de dados ou seja, qual a distribuição de frequências dos dados?
> ii) Quais são alguns valores típicos do conjunto de dados, como mínimo e máximo?
> iii) Qual seria um valor para representar a posição (ou localização) central do conjunto de dados?
> iv) Qual seria uma medida da variabilidade ou dispersão dos dados?
> v) Existem valores atípicos ou discrepantes (outliers) no conjunto de dados?
> vi) A distribuição de frequências dos dados pode ser considerada simétrica? 
>
> [@MorettinSinger2022, p. 37]

## Distribuição de frequências

Sem notas para esta seção.

## Medidas resumo

> Dado um número $0 < \alpha < 1$, a **média aparada** de ordem $\alpha$, $\overline{x}(\alpha)$, é definida como a média do conjunto de dados obtido após a eliminação das 100% primeiras observações ordenadas e das 100% últimas observações ordenadas do conjunto original [...]. Para $\alpha = 0,25$ obtemos a chamada **meia média**. [@MorettinSinger2022, p. 47]. 

Dado um número natural $k \geq 2$ e um conjunto $X = \{x_{1}, \cdots, x_{n}\}$ com $n \in \mathbb{N}$, o $k$-ésimo **momento centrado** de X é dado por [@MorettinSinger2022, p. 50]:

$$m_{k} = \frac{1}{n}\sum_{i = 1}^{n}(x_{i} - \overline{x})^{k}$$

> Dentre as medidas de assimetria, as mais comuns são:
>
> a) o coeficiente de assimetria de Fisher-Pearson: $$g_{1} = \frac{m_{3}}{m_{2}^{(3/2)}}$$
> b) o coeficiente de assimetria de Fisher-Pearson ajustado: $$\frac{\sqrt{n (n - 1)}}{n - 2} g_{1}$$
> [@MorettinSinger2022, p. 50]


> As principais propriedades desses coeficientes são
>
> i) seu sinal reflete a direção da assimetria (sinal negativo corresponde a assimetria à direita e sinal positivo corresponde a assimetria à esquerda);
> ii) comparam a assimetria dos dados com aquela da distribuição normal, que é simétrica,
> iii) valores mais afastados do zero indicam maiores magnitudes de assimetria e consequente- mente, maior afastamento da distribuição normal;
> iv) a estatística indicada em (3.15) tem um ajuste para o tamanho amostral;
> v) esse ajuste tem pequeno impacto em grandes amostras.
> [@MorettinSinger2022, p. 51]

> Outro coeficiente de assimetria mais intuitivo é o chamado **coeficiente de assimetria de Pearson 2**, estimado por $$Sk_{2} = \frac{3 \cdot [ x - med(x_{1}, \cdots, x_{n})]}{S}$$ [@MorettinSinger2022, p. 51].

> Seja $X$ uma variável aleatória qualquer, com média $\mu$ e variância $\sigma^{2}$. A **curtose** de $X$ é definida por $$K(X) = E \left[ \frac{(X - \mu)^{4}}{\sigma^{4}} \right]$$ [@MorettinSinger2022, p. 53]

## _Boxplots_

Sem notas para esta seção.

## Modelos probabilísticos

Sem notas para esta seção.

## Dados amostrais

Sem notas para esta seção.

## Gráficos QQ

> Uma das questões fundamentais na especificação de um modelo para inferência estatística é a escolha de um modelo probabilístico para representar a distribuição (desconhecida) da variável de interesse na população. Uma possível estratégia para isso é examinar o histograma dos dados amostrais e compará-lo com histogramas teóricos associados a modelos probabilísticos candidatos. Alternativamente, os gráficos QQ (QQ plots) também podem ser utilizados com essa finalidade  [@MorettinSinger2022, p. 59].

## Desvio padrão e erro padrão

Sem notas para esta seção.

## Intervalo de confiança e tamanho da amostra

> [...] **margem de erro**, que, essencialmente, é uma medida de nossa incerteza na extrapolação dos resultados obtidos para a população de onde assumimos que foi obtida  [@MorettinSinger2022, p. 65].

> A margem de erro depende do processo amostral, do desvio padrão amostral $S$, do tamanho da amostra $n$ e é dado por $me = \frac{kS}{\sqrt{n}}$ em que $k$ é uma constante que depende do modelo probabilístico adotado e da confiança com que pretendemos fazer a inferência [@MorettinSinger2022, p. 65].

> Especificamente no caso da estimação da média (populacional) $\mu$ de uma variável $X$, a pergunta seria *Qual é o tamanho da amostra necessário para que a estimativa* $\overline{X}$ *da média* $\mu$ *tenha uma precisão* $\varepsilon$*?* A resposta pode ser obtida da expressão (3.21), fazendo $\varepsilon = \frac{1,96 \cdot S}{\sqrt{n}}$ [@MorettinSinger2022, p. 66].

## Transformação de variáveis

> Se quisermos utilizar os procedimentos talhados para análise de dados com distribuição normal em situações nas quais a distribuição dos dados amostrais é sabidamente assimétrica, pode-se considerar uma transformação das observações com a finalidade de se obter uma distribuição "mais simétrica" e portanto, mais próxima da distribuição normal. Uma transformação bastante usada com esse propósito é 
>
$$
x^{(p)} =
  \begin{cases}
    x^{p}, & se \ p > 0 \\
    log(x), & se \ p = 0 \\
    -x^{p}, & se \ p < 0
  \end{cases}
$$
>
> Essa transformação com $0 < p < 1$ apropriada para distribuições assimétricas à direita, pois valores grandes decrescem de $x$ decrescem mais relativamente a valores pequenos. Para distribuições assimétricas à esquerda, basta tomar $p > 1$. Normalmente, consideramos valores de $p$ na sequência 
>
> $$\cdots, -3, -2, -1, -1/2, -1/3, -1/4, 0, 1/4, 1/3, 1/2, 1, 2, 3, \cdots$$ 
>
> e para cada um deles construímos gráficos apropriados (histogramas, boxplots) com os dados originais transformados, com a finalidade de escolher o valor mais adequado para $p$. Hinkley (1977) sugere que para cada valor de $p$ na sequência acima se calcule a média, a mediana e um estimador de escala (esvio padrão ou algum estimador robusto) e então se escolha o valor que minimiza 
>
>$$d_{p} = \frac{média - mediana}{medida \ de \ escala}$$
>
>[@MorettinSinger2022, p. 67].


> A transformação (3.23) [acima] é um caso particular das **transformações de Box-Cox** que são da forma
>
$$
g(x) = 
  \begin{cases}
    \frac{(x^{p} - 1)}{p}, & se \ p \neq 0 \\
    log(x), & se \ p = 0
  \end{cases}
$$
>
> [@MorettinSinger2022, p. 69].

## Notas de capítulo

Sem notas para esta seção.

## Exercícios

### Exercício 3.1 {- #exr3-1}

::: {.enunciado}
O arquivo `rehabcardio.xls` contém informações sobre um estudo de reabilitação de pacientes cardiacos. Elabore um relatório indicando possíveis inconsistências na matriz de dados e faça uma análise descritiva das variáveis `Peso`, `Altura`, `Coltot`, `HDL`, `LDL`, `Lesces`, `Diabete` e `RA`. Com essa finalidade,

a) Construa distribuições de frequências para as variáveis qualitativas.
b) Construa histogramas, *boxplots* e gráficos de simetria para as variáveis continuas.
c) Construa uma tabela com medidas resumo para as variáveis continuas.
d) Avalie a compatibilidade de distribuições normais para as variáveis continuas por meio de gráficos QQ.
:::

:::{.solution}
x
:::

### Exercício 3.2 {- #exr3-2}

::: {.enunciado}
Considere os dados do arquivo `antracose.xls`.

a) Construa uma tabela com as medidas de posição e dispersão estudadas para as variáveis desse arquivo 
b) Construa histogramas e boxplots para essas variáveis e verifique que transformação é necessária para tornar mais simétricas aquelas em que a simetria pode ser questionada. 
:::

:::{.solution}
x
:::

### Exercício 3.3 {- #exr3-3}

::: {.enunciado}
Considere as variáveis Peso e Altura de homens do conjunto de dados rehabcardio. Determine o número de classes para os histogramas correspondentes por meio de (3.26) e (3.27) e construa-os.
:::

:::{.solution}
x
:::

### Exercício 3.4 {- #exr3-4}

::: {.enunciado}
Considere o arquivo `vento.xls`. Observe o valor atipico $61,1$, que na realidade ocorreu devido a uma forte tempestade no dia 2 de dezembro. Calcule as medidas de posição e dispersão apresentadas na Seção 3.3. Quantifique o efeito do valor atipico indicado nessas medidas.
:::

:::{.solution}
x
:::

### Exercício 3.5 {- #exr3-5}

::: {.enunciado}
Construa gráficos ramo-e-folhas e boxplot para os dados do [Exercício 4](#exr3-4).
:::

:::{.solution}
x
:::

### Exercício 3.6 {- #exr3-6}

::: {.enunciado}
Transforme os dados do [Exercicio 4](#exr3-4) por meio de (3.23) com $p = 0, 1/4, 1/3, 1/2, 3/4$ e escolha a melhor alternativa de acordo com a medida $d_{p}$, dada em (3.24).
:::

:::{.solution}
x
:::

### Exercício 3.7 {- #exr3-7}

::: {.enunciado}
Analise a variável Temperatura do arquivo `poluicao.xls`.
:::

:::{.solution}
x
:::

### Exercício 3.8 {- #exr3-8}

::: {.enunciado}
Analise a variável `Salário de administradores`, disponível no arquivo `salarios.xls`.
:::

:::{.solution}
x
:::

### Exercício 3.9 {- #exr3-9}

::: {.enunciado}
Construa um gráfico ramo-e-folhas e um boxplot para os dados de precipitação atmosférica de Fortaleza disponíveis no arquivo precipitacao. manchas solares disponiveis no arquivo `manchas.xls`.
:::

:::{.solution}
x
:::

### Exercício 3.10 {- #exr3-10}

::: {.enunciado}
Construa gráficos de quantis e de simetria para os dados de arquivo manchas solares  disponíveis no arquivo `manchas.xls`.
:::

:::{.solution}
x
:::

### Exercício 3.11 {- #exr3-11}

::: {.enunciado}
Uma outra medida de assimetria é $$ A = \frac{(Q_{3} - Q_{2}) - (Q_{2} - Q_{1})}{Q_{3} - Q_{1}},$$ que é iual a zero no caso de distribuições simétricas. Calcule-a para os dados do [Exercício 4](#exr3-4).
:::

:::{.solution}
x
:::

### Exercício 3.12 {- #exr3-12}

::: {.enunciado}
Os dados disponíveis no arquivo `endometrione.xls` são provenientes de um estudo em que o objetivo é verificar se existe diferença entre os grupos de doentes e controles quanto a algumas caracteristicas observadas.

a) O pesquisador responsável pelo estudo tem a seguinte pergunta: pacientes doentes apresentam mais dor na menstruação do que as pacientes não doentes? Que tipo de análise você faria para responder essa pergunta utilizando as técnicas discutidas neste capitulo? Faça-a e tire suas conclusões.
b) Compare as distribuições das variáveis idade e concentração de PCR durante a menstruação (`PCRa`) para pacientes dos grupos controle e doente utilizando medidas resumo (minimo, máximo, quartis, mediana, média, desvio padrão, etc.), *boxplots*, histogramas, gráficos de médias e gráficos QQ. Como você considerou os valores $< 0,5$ da variável `PCRa` nesses cálculos? Você sugeriria uma outra maneira para considerar tais valores?
c) Compare a distribuição da variável número de gestações para os dois grupos por intermédio de uma tabela de frequências. Utilize um método gráfico para representá-la.
:::

:::{.solution}
x
:::

### Exercício 3.13 {- #exr3-13}

::: {.enunciado}
Os dados encontrados no arquivo `enforco.xls` são provenientes de um estudo sobre teste de esforço cardiopulmonar em pacientes com insuficiência cardíaca. As variáveis medidas durante a realização do teste foram observadas em quatro momentos distintos: repouso (REP), limiar anaeróbico (LAN), ponto de compensação respiratório (PCR) e pico (PICO). As demais variáveis são referentes às características demográficas e clinicas dos pacientes e foram registras uma única vez.

a) Descreva a distribuição da variável consumo de oxigênio (`VO2`) em cada um dos quatro momentos de avaliação utilizando medidas resumo (mínimo, máximo, quartis, mediana, média, desvio padrão, etc.), *boxplots* e histogramas. Você identifica algum paciente com valores de consumo de oxigênio discrepantes? Interprete os resultados.
b) Descreva a distribuição da classe funcional NYHA por meio de uma tabela de frequências. Utilize um método gráfico para representar essa tabela.
:::

:::{.solution}
x
:::

### Exercício 3.14 {- #exr3-14}

::: {.enunciado}
Na tabela abaixo estão indicadas as durações de 335 lâmpadas.

Duração (horas)  | Número de lâmpadas
:---------------:|:------------------:
$0 \vdash 100$   | 82
$100 \vdash 200$ | 71
$200 \vdash 300$ | 68
$300 \vdash 400$ | 56
$400 \vdash 500$ | 43
$500 \vdash 800$ | 15

a) Esboce o histograma correspondente.
b) Calcule os quantis de ordem $p = 0,1, 0,3, 0,5, 0,7$ e $0,9$.
:::

:::{.solution}
x
:::

### Exercício 3.15 {- #exr3-15}

::: {.enunciado}
Os dados apresentados na tabela abaixo referem-se aos instantes nos quais o centro de controle operacional de estradas rodoviárias recebeu chamados solicitando algum tipo de auxilio em duas estradas num determinado dia.

|           |             |             |             |             |             |
|:---------:|:-----------:|:-----------:|:-----------:|:-----------:|:-----------:|
| Estrada 1 | 12:07:00 AM | 15:58:00 AM | 01:24:00 AM | 01:35:00 AM | 02:05:00 AM |
|           | 03:14:00 AM | 03:25:00 AM | 03:46:00 AM | 05:44:00 AM | 05:56:00 AM |
|           | 06:36:00 AM | 07:26:00 AM | 07:48:00 AM | 09:13:00 AM | 12:05:00 PM |
|           | 12:48:00 PM | 01:21:00 PM | 02:22:00 PM | 05:30:00 PM | 06:00:00 PM |
|           | 07:53:00 PM | 09:15:00 PM | 09:49:00 PM | 09:59:00 PM | 10:53:00 PM |
|           | 11:27:00 PM | 11:49:00 PM | 11:57:00 PM |             |             |
| Estrada 2 | 12:03:00 AM | 01:18:00 AM | 04:35:00 AM | 06:13:00 AM | 06:59:00 AM |
|           | 08:03:00 AM | 10:07:00 AM | 12:24:00 PM | 01:45:00 PM | 02:07:00 PM |
|           | 03:23:00 PM | 06:34:00 PM | 07:19:00 PM | 09:44:00 PM | 10:27:00 PM |
|           | 10:52:00 PM | 11:19:00 PM | 11:29:00 PM | 11:44:00 PM |             |

a) Construa um histograma para a distribuição de frequências dos instantes de chamados em cada uma das estradas. 
b) Calcule os intervalos de tempo entre as sucessivas chamadas e descreva-os, para cada uma das estradas, utilizando medidas resumo e gráficos do tipo *boxplot*. Existe alguma relação entre o tipo de estrada e o intervalo de tempo entre as chamadas?
c) Por intermédio de um gráfico do tipo QQ, verifique se a distribuição da variável `Intervalo de tempo entre as chamadas` em cada estrada é compatível com um modelo normal. Faça o mesmo para um modelo exponencial. Compare as distribuições de frequências correspondentes às duas estradas.
:::

:::{.solution}
x
:::

### Exercício 3.16 {- #exr3-16}

::: {.enunciado}
As notas finais de um curso de Estatistica foram: 7, 5, 4, 5, 6, 3, 8, 4, 5, 4, 6, 4, 5, 6, 4, 6, 6, 3, 8, 4, 5, 4, 5, 5 e 6.

a) Calcule a mediana, os quartis e a média.
b) Separe o conjunto de dados em dois grupos denominados **aprovados**, com nota pelo menos igual a 5, e **reprovados**, com notas menores do que 5. Compare a variáncia das notas desses dois grupos.
:::

:::{.solution}
x
:::

### Exercício 3.17 {- #exr3-17}

::: {.enunciado}
Considere o seguinte resumo descritivo da pulsação de estudantes com atividade fisica intensa e fraca:

Atividade | N   | Media | Mediana | DP   | Min | Max | Q1  | Q3
:---------|:---:|:-----:|:-------:|:----:|:---:|:---:|:---:|:---:
Intensa   | 30  | 79,6  | 82      | 10,5 | 62  | 90  | 70  | 85
Fraca	    | 30  | 73,1  | 70      | 9,6  | 58  | 92  | 63  | 77

Indique se as seguintes afirmações estão corretas, justificando a sua respostas:

a) 5% e 50% dos estudantes com atividade fisica intensa e fraca, respectivamente, tiveram pulsação inferior a 70. 
b) A proporção de estudantes com fraca atividade fisica com pulsação inferior a 63 é menor que a proporção de estudantes com atividade fisica intensa com pulsação inferior a 70. 
c) A atividade fisica não tem efeito na média da pulsação dos estudantes. 
d) Mais da metade dos estudantes com atividade fisica intensa têm pulsação maior que 82.
:::

:::{.solution}
x
:::

### Exercício 3.18 {- #exr3-18}

::: {.enunciado}
Considere os gráficos *boxplot* da Figura 3.34. Quais deles correspondem às pulsações dos estudantes submetidos a atividade física intensa e fraca?

a) A e B
b) B e D
c) A e C
d) B e C
:::

:::{.solution}
x
:::

### Exercício 3.19 {- #exr3-19}

::: {.enunciado}
Os histogramas apresentados na Figura 3.35 mostram a distribuição das temperaturas (°C) ao longo de vários dias de investigação para duas regiões (R1 e R2). Indique se as afirmações abaixo estão corretas, justificando as respostas:

a) As temperaturas das regiões R1 e R2 têm mesma média e mesma variância.
b) Não é possível comparar as variâncias.
c) A temperatura média da região R2 é maior que a de R1.
d) As temperaturas das regiões R1 e R2 têm mesma média e variância diferentes.
:::

:::{.solution}
x
:::

### Exercício 3.20 {- #exr3-20}

::: {.enunciado}
Na companhia A, a média dos salários é 10000 unidades e o 3 quartil é 5000. Responda as seguintes perguntas, justificando a sua respostas:

a) Se você se apresentasse como candidato a funcionário nessa firma e se o seu salário fosse escolhido ao acaso entre todos os possíveis salários, o que seria mais provável: ganhar mais ou menos que 5000 unidades?
b) Suponha que na companhia B a média dos salários seja 7000 unidades, a variância praticamente zero e o salário também seja escolhido ao acaso. Em qual companhia você se apresentaria para procurar emprego, com base somente no salário?
:::

:::{.solution}
x
:::

### Exercício 3.21 {- #exr3-21}

::: {.enunciado}
Num conjunto de dados, o primeiro quartil é 10, a mediana é 15 e o terceiro quartil é 20. Indique quais das seguintes afirmativas são verdadeiras, justificando sua resposta:

a) A distância interquartis é 5.
b) O valor 32 seria considerado outlier segundo o critério utilizado na construção do boxplot.
c) A mediana ficaria alterada de 2 unidades se um ponto com valor acima do terceiro quartil fosse substituído por outro 2 vezes maior. 
d) O valor mínimo é maior do que zero.
:::

:::{.solution}
x
:::

### Exercício 3.22 {- #exr3-22}

::: {.enunciado}
A bula de um medicamento A para dor de cabeça afirma que o tempo médio para que a droga faça efeito é de 60 seg com desvio padrão de 10 seg. A bula de um segundo medicamento B afirma que a média correspondente é de 60 seg com desvio padrão de 30 seg. Sabe-se que as distribuições são simétricas. Indique quais das seguintes afirmativas são verdadeiras, justificando sua resposta:

a) Os medicamentos são totalmente equivalentes com relação ao tempo para efeito pois as médias são iguais. 
b) Com o medicamento A, a probabilidade de cura de sua dor de cabeça antes de 40 seg é maior do que com o medicamento B. 
c) Com o medicamento B, a probabilidade de você ter sua dor de cabeça curada antes de 60 seg é maior que com o medicamento A. 
:::

:::{.solution}
x
:::

### Exercício 3.23 {- #exr3-23}

::: {.enunciado}
A tabela abaixo representa a distribuição do número de dependentes por empregado de uma determinada empresa.

Dependentes | Frequência
:----------:|:-----------:
1           | 40
2           | 50
3           | 30
4           | 20
5           | 10
Total       | 150

A mediana, média e moda cujos valores calculados por quatro estagiários, foram: 

a) 50; 15; 50 
b) 1; 2,1; 1 
c) 50,5; 50; 50 
d) 1; 1; 1

Indique qual deles está correto, justificando sua resposta.
:::

:::{.solution}
x
:::

### Exercício 3.24 {- #exr3-24}

::: {.enunciado}
Com relação ao [Exercício 23](#exr3-23), qual a porcentagem de empregados da empresa com 2 ou mais dependentes?

a) 40,1%
b) 50,1%
c) 60,3%
d) 73,3%
:::

:::{.solution}
x
:::

### Exercício 3.25 {- #exr3-25}

::: {.enunciado}
Num estudo na área de Oncologia, o número de vasos que alimentam o tumor está resumido na seguinte tabela.

Número de vasos | Frequência
:--------------:|:----------:
$0 \vdash 5$    | 8 (12%)
$5 \vdash 10$   | 23 (35%)
$10 \vdash 15$  | 12 (18%)
$15 \vdash 20$  | 9 (14%)
$20 \vdash 25$  | 8 (12%)
$25 \vdash 30$  | 6 (9%)
Total           | 66 (100%)

Indique a resposta correta.

a) O primeiro quartil é 25%. 
b) A mediana está entre 10 e 15.
c) O percentil de ordem 10% é 10.
d) A distância interquartis é 50.
e) Nenhuma das respostas anteriores.
:::

:::{.solution}
x
:::

### Exercício 3.26 {- #exr3-26}

::: {.enunciado}
Utilizando o mesmo enunciado da questão anterior, indique a resposta correta: 

a) Não é possível estimar nem a média nem a variância com esses dados.
b) A variancia é menor que 30.
c) A média estimada é 12,8. 
d) Em apenas 35% dos casos, o número de vasos é maior que 10.
e) Nenhuma das anteriores.
:::

:::{.solution}
x
:::

### Exercício 3.27 {- #exr3-27}

::: {.enunciado}
Em dois estudos realizados com o objetivo de estimar o nivel médio de colesterol total para uma população de indivíduos saudáveis observaram-se os dados indicados na tabela seguinte:

Estudo | n   | Média     | Desvio padrão
:-----:|:---:|:---------:|:-------------:
A      | 100 | 160 mg/dL | 60 mg/dL
B      | 49  | 150 mg/dL | 35 mg/dL
: **Tabela A:** Medidas descritivas dos estudos A e B

Indique a resposta correta:

a) Não é possível estimar o nível médio de colesterol populacional só com esses dados.
b) Se os dois estudos foram realizados com amostras da mesma população não deveria haver diferença entre os desvios padrões amostrais.
c) Com os dados do estudo B, o colesterol médio populacional pode ser estimado com mais precisão do que com os dados do estudo A.
d) Ambos os estudos sugerem que a distribuição do colesterol na população é simétrica.
e) Nenhuma das respostas anteriores.
:::

:::{.solution}
x
:::

### Exercício 3.28 {- #exr3-28}

::: {.enunciado}
Considere um conjunto de dados $\{X_{1}, \cdots , X_{n}\}$

a) Obtenha a média e a variancia de $W_{1}, \cdots , W_{n}$ em que $W_{l} = X_{l} + k$ com $k$ denotando uma constante, em termos da média e da variancia de $X$. 
b) Calcule a média e a variância de $v_{1}, \cdots , V_{n}$ em que $V_{i} = kX_{i}$ com $k$ denotando uma constante, em termos da média e da variancia de $X$.
:::

:::{.solution}
x
:::

### Exercício 3.29 {- #exr3-29}

::: {.enunciado}
Prove que $S^{2}$ dado por (3.10) é um estimador não enviesado da variáncia populacional.
:::

:::{.solution}
x
:::

### Exercício 3.30 {- #exr3-30}

::: {.enunciado}
Considere os valores $X_{1}, \cdots , X_{n}$ de uma variável $X$, com média $\overline{X}$ e desvio padrão $S$. Mostre que a variável $Z$, cujos valores são $Z_{i} = (X_{i} - X) / S, \ i = 1, \cdots , n$, tem média 0 e desvio padrão 1.
:::

:::{.solution}
x
:::

### Exercício 3.31 {- #exr3-31}

::: {.enunciado}
Prove a relação (3.8). Como ficaria essa expressão para $S^{2}$?
:::

:::{.solution}
x
:::

### Exercício 3.32 {- #exr3-32}

::: {.enunciado}
Considere uma amostra aleatória simples $X_{1}, \cdots , X_{n}$ de uma variável $X$ que assume o valor 1 com probabilidade $0 < p < 1$ e o valor 0 com probabilidade $1 - p$. Seja $\hat{p} = n^{-1} \sum_{i=1}^{n} X_{i}$. Mostre que:

i) $E(X_{i}) = p$ e $Var(X_{i}) = p (1 - p)$.
ii) $E(\hat{p}) = p$ e $Var(\hat{p}) = p (1 - p) / n$.
iii) $0 < Var(X_{i}) < 0,25$.

Com base nesses resultados, utilize o Teorema Limite Central [ver Sen et al. (2009), por exemplo] para construir um intervalo de confiança aproximado conservador (ie, com a maior amplitude possível) para $p$. Utilize o Teorema de Sverdrup [ver Sen et al. (2009), por exemplo] para construir um intervalo de confiança aproximado para $p$ com amplitude menor que a do intervalo mencionado acima. Veja também, Bussab e Morettin (2017).
:::

:::{.solution}
x
:::

### Exercício 3.33 {- #exr3-33}

::: {.enunciado}
Com a finalidade de entender a diferença entre "desvio padrão" e "erro padrão",

a) Simule 10000 dados de uma distribuição normal com média 12 e desvio padrão 4. Construa o histograma correspondente, calcule a média e o desvio padrão amostrais e compare os valores obtidos com aqueles utilizados na geração dos dados.
b) Simule 500 amostras de tamanhon $n = 4$ dessa população. Calcule a média amostral de cada amostra, construa o histograma dessas médias e estime o correspondente desvio padrão (que é o erro padrão da média).
c) Repita os passos a) e b) com amostras de tamanhos $n = 9$ e $n = 100$. Comente os resultados comparando-os com aqueles preconizados pela teoria.
d) Repita os passos a) - c) simulando amostras de uma distribuição qui-quadrado com 3 graus de liberdade.
:::

:::{.solution}
x
:::